apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: anomaly-detector-lag-analyzer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: anomaly-detector-lag-analyzer
              image: anomaly-detector/lag-analyzer:1.0-SNAPSHOT
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure