apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: anomaly-detector-alert-processor
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: anomaly-detector-alert-processor
              image: anomaly-detector/alert-processor:1.0-SNAPSHOT
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure